branches:
  only:
    - master

# Start builds on tags only
# skip_non_tags: true

environment:
  matrix:
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32

build_script:
  - set
  - set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
  - set CHERE_INVOKING=yes
  - wget https://www.paralint.com/projects/notifu/dl/notifu-src-1.6.1.zip
  - bash -lc 'exec test $(sha256sum notifu-src-1.6.1.zip | cut -d " " -f0) eq 0fdcd08d3e12d87af76cdaafbf1278c4fcf1baf5d6447cce1a676b8d78a4d8c3"
  - unzip notifu-src-1.6.1.zip
  - MSBuild.exe .\notifu.sln /p:Configuration=Debug /p:Platform=WIN32
  - bash -lc "cp Debug/notifu.exe tools/win_installer/misc"
  - bash -lc "pacman --noconfirm --ask 20 -Suy"
  - bash -lc "bash .appveyor/msys2.sh"

artifacts:
  - path: tools/win_installer/gpodder-*-contents.txt
  - path: tools/win_installer/gpodder-*-installer.exe
  - path: tools/win_installer/gpodder-*-portable.exe

deploy: off