language: python
dist: trusty
sudo: required
python:
    - "3.5"
install:
    - sudo apt-get update -q
    - sudo apt-get install intltool desktop-file-utils
    - pip3 install pytest-cov minimock pycodestyle isort requests pytest pytest-httpserver
    - python3 tools/localdepends.py
script:
    - make lint
    - make releasetest
