language: python
dist: trusty
sudo: required
python:
    - "3.5"
install:
    - sudo apt-get update -q
    - sudo apt-get install intltool desktop-file-utils
    - pip3 install coverage minimock pycodestyle isort
    - python3 tools/localdepends.py
script:
    - pycodestyle share src/gpodder tools bin/* *.py
    - make releasetest
